# Generated by Django 4.0.1 on 2022-02-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_rename_xid_tripevent_place_id_tripevent_place_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripevent',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tripevent',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
