# Generated by Django 4.0.1 on 2022-02-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0005_alter_tripevent_end_time_alter_tripevent_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripevent',
            name='place_name',
            field=models.CharField(default='default_place_name', max_length=64),
            preserve_default=False,
        ),
    ]
