# Generated by Django 4.0.1 on 2022-03-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0006_tripevent_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripevent',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripevent',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
